import header from './images/header.png';
import fondo1 from './images/fondo1.png';
import logo from './images/logo.svg';
import './css/App.css';
import { Ram } from './components/Ram';
import { GraficaPie } from './components/GraficaPie';
import { useEffect, useState } from 'react';
import { Parallax } from 'react-parallax';

import { Heading } from './components/Heading';


function App() {
    return(
      <div className='div-body'>
      <Heading/>
      <Parallax blur={{ min: -15, max: 15 }} bgImage={header}>
      <header className='header'>
        <h1>Linux Easy Admin</h1>
        <p>Bienvenido a Linux Easy Admin, tener el control de tu PC en Linux nunca había sido tan fácil</p>

      </header>
      </Parallax>
      <Parallax bgImage={fondo1}>
      <div className='div-cuerpo'>
        <div className='div-ram'>
          <h3>Memoria Ram:</h3>
          <div className='div-pie'>
          <GraficaPie />
          </div>
        </div>
      <div className='prueba'>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>
        <p>MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR MDLR</p>

      </div>
      </div>
      </Parallax>
      </div>






    )
}

export default App;
